export const elements = {
    moviewrapper : document.querySelector('.movie-wrapper'),
    trending__moviewrapper : document.querySelector('.trending__movie-wrapper'),
    trailer__wrapper : document.querySelector('.trailer-card__wrapper'),
    tvshows__wrapper : document.querySelector('.latest__movie-wrapper'),
    movieInfo_container : document.querySelector('.movie-info__container'),
    topcast_scroller : document.querySelector('.top-cast__scroller'),
    media_content : document.querySelector('.media-content'),
    media_content__scroller : document.querySelector('.media-content__scroller'),
    rcmd_content__scroller : document.querySelector('.rcmd-content__scroller'),
    full_cast : document.querySelector('.full-cast'),
    content_cast__card__wrapper : document.querySelector('.content-cast__card--wrapper'),
    content_crew__card__wrapper : document.querySelector('.content-crew__card--wrapper'),
    crew_cast__header : document.querySelector('.cast-crew__header'),
    people_info_wrapper : document.querySelector('.people-info__wrapper'),
    nav_movie__title : document.querySelector('.nav__movie--title'),
    nav_movie__content : document.querySelector('.nav__movie--content'),
    nav_tv__content : document.querySelector('.nav__tv--content'),
    nav_tv__title : document.querySelector('.nav__tv--title'),
    person_cards__wrapper : document.querySelector('.person__cards--wrapper'),
    search__form__button : document.querySelector('.search__form--button'),
    search__form__textbox : document.querySelector('.search__form--textbox'),
    search__content : document.querySelector('.search__content'),
    search__query : document.querySelector('.search__query'),
    search__nav_link__movies : document.querySelector('.search__nav-link--movies'),
    search__nav_link__tv : document.querySelector('.search__nav-link--tv'),
    search__nav_link__people : document.querySelector('.search__nav-link--people')
}

